//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cloudmp3
{
    using System;
    using System.Collections.Generic;
    
    public partial class Song
    {
        public Song()
        {
            this.Playlists = new HashSet<Playlist>();
        }
    
        public int S_Id { get; set; }
        public string S_Title { get; set; }
        public string S_Path { get; set; }
        public int S_OwnerId { get; set; }
        public string S_Artist { get; set; }
        public Nullable<int> S_Length { get; set; }
    
        public virtual User User { get; set; }
        public virtual ICollection<Playlist> Playlists { get; set; }
    }
}
