//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cloudmp3
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public User()
        {
            this.Playlists = new HashSet<Playlist>();
            this.Songs = new HashSet<Song>();
        }
    
        public int U_Id { get; set; }
        public string U_UserName { get; set; }
        public string U_Password { get; set; }
    
        public virtual ICollection<Playlist> Playlists { get; set; }
        public virtual ICollection<Song> Songs { get; set; }
    }
}
